name: Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    name: Create update
    type: update
    params:
      branch: pr-${{ github.event.pull_request.number }}
      message: "PR #${{ github.event.pull_request.number }}"

  comment:
    name: Post QR code
    needs: [publish]
    type: github-comment
